name: Locale Lint
on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  locale:
    uses: OpenVoiceOS/gh-automations/.github/workflows/locale-lint.yml@feat/locale-lint-workflow
    secrets: inherit
